    print("Hello Wordr")
    print("我叫张小成")
    print("   *")
    print("  ***")
    print(" *****")
    print("*******")
    N=100
    print(N)
    input("请输入：")
    n=int(input("请输入海绵宝宝的年龄："))
    m=int(input("请输入派大星的年龄："))
    print("他们的年龄和为：",n+m)
